const SUPA_URL='https://sijaphinxdufumwqlabb.supabase.co';
const SUPA_KEY='sb_publishable_yfGHY6mNRZ-2jWdb1P5N_A_fgxR8f1z';
const LS='ielts-focus-state-v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
import {names,BANK} from './data.js';
let state=load(),mode='single',queue=[],idx=0,current=null,prepStarted=0,prepTimer=null,armed=false,selected=[],matchValues=[],sessionResults=[],client=null,user=null,syncTimer=null;
function baseState(){return{answers:{},sessions:0,streak:0,bestStreak:0,seen:{single:[],multi:[],matching:[]},updatedAt:0}}
function load(){try{return {...baseState(),...JSON.parse(localStorage.getItem(LS)||'{}')}}catch{return baseState()}}
function save(){state.updatedAt=Date.now();localStorage.setItem(LS,JSON.stringify(state));renderStats();scheduleSync()}
function merge(a,b){const out=baseState();out.sessions=Math.max(a.sessions||0,b.sessions||0);out.bestStreak=Math.max(a.bestStreak||0,b.bestStreak||0);out.streak=(a.updatedAt||0)>=(b.updatedAt||0)?a.streak||0:b.streak||0;out.updatedAt=Math.max(a.updatedAt||0,b.updatedAt||0);for(const t of ['single','multi','matching'])out.seen[t]=[...new Set([...(a.seen?.[t]||[]),...(b.seen?.[t]||[])])].slice(-200);const keys=new Set([...Object.keys(a.answers||{}),...Object.keys(b.answers||{})]);for(const k of keys){const x=a.answers?.[k],y=b.answers?.[k];out.answers[k]=!x?y:!y?x:(x.lastAt||0)>=(y.lastAt||0)?x:y}return out}
function renderStats(){const a=Object.values(state.answers||{});const attempts=a.reduce((n,x)=>n+(x.attempts||0),0),points=a.reduce((n,x)=>n+(x.correct||0),0),maxPoints=a.reduce((n,x)=>n+(x.maxPoints||x.attempts||0),0),pre=a.reduce((n,x)=>n+(x.armed||0),0);$('#stDone').textContent=attempts;$('#stAcc').textContent=maxPoints?Math.round(points/maxPoints*100)+'%':'—';$('#stPre').textContent=attempts?Math.round(pre/attempts*100)+'%':'—';$('#stStreak').textContent=state.streak||0}
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});
$('#startBtn').onclick=start;$('#againBtn').onclick=start;$('#homeBtn').onclick=()=>show('home');$('#authToggle').onclick=()=>$('#authPanel').classList.toggle('hidden');
function show(id){for(const x of ['home','session','summary'])$('#'+x).classList.toggle('hidden',x!==id)}
function pickQuestions(){const count=+$('#countSel').value,bank=BANK[mode],seen=new Set(state.seen[mode]||[]),fresh=bank.filter(q=>!seen.has(q.id));const pool=[...fresh,...bank.filter(q=>seen.has(q.id))];pool.sort(()=>Math.random()-.5);return pool.slice(0,count)}
function start(){queue=pickQuestions();idx=0;sessionResults=[];show('session');next()}
function next(){clearInterval(prepTimer);if(idx>=queue.length)return finish();current=queue[idx];selected=[];matchValues=[];armed=false;prepStarted=performance.now();$('#progressText').textContent=`${idx+1} / ${queue.length}`;$('#progressBar').style.width=((idx)/queue.length*100)+'%';$('#phaseText').textContent='选项上膛';$('#preloadBox').classList.remove('hidden');$('#listenBox').classList.add('hidden');$('#stem').textContent=current.stem;$('#axisText').textContent=current.axes.map((x,i)=>String.fromCharCode(65+i)+' '+x).join('  /  ');renderPre();let left=+$('#prepSel').value;$('#prepTimer').textContent=left+' 秒';prepTimer=setInterval(()=>{left--;$('#prepTimer').textContent=Math.max(0,left)+' 秒';if(left<=0){clearInterval(prepTimer);enterListen(false)}},1000)}
function renderPre(){$('#preOptions').innerHTML=current.options.map((o,i)=>`<div class="opt"><b>${String.fromCharCode(65+i)}</b><span>${o}</span></div>`).join('')}
$('#armedBtn').onclick=()=>enterListen(true);
function enterListen(ok){if(!current)return;clearInterval(prepTimer);armed=ok;const lag=Math.round(performance.now()-prepStarted);current._prepLag=lag;$('#phaseText').textContent='带着选项听';$('#preloadBox').classList.add('hidden');$('#listenBox').classList.remove('hidden');$('#listenStem').textContent=current.stem;$('#matchingAnswers').innerHTML='';if(current.type==='matching'){renderMatching()}else renderAnswers();setTimeout(playAudio,250)}
function renderAnswers(){$('#answerOptions').innerHTML=current.options.map((o,i)=>`<button class="opt" data-i="${i}" type="button"><b>${String.fromCharCode(65+i)}</b><span>${o}</span></button>`).join('');$$('#answerOptions .opt').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;if(current.type==='single'){selected=[i];$$('#answerOptions .opt').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')}else{if(selected.includes(i))selected=selected.filter(x=>x!==i);else if(selected.length<2)selected.push(i);$$('#answerOptions .opt').forEach(x=>x.classList.toggle('sel',selected.includes(+x.dataset.i)))}})}
function renderMatching(){$('#answerOptions').innerHTML='<div class="muted">共享选项：'+current.options.map((o,i)=>String.fromCharCode(65+i)+' '+o).join(' · ')+'</div>';$('#matchingAnswers').innerHTML=current.lines.map((_,i)=>`<div class="match-row"><b>${names[i]} / Item ${i+1}</b><select data-mi="${i}"><option value="">请选择</option>${current.options.map((o,j)=>`<option value="${j}">${String.fromCharCode(65+j)} ${o}</option>`).join('')}</select></div>`).join('')}
function playAudio(){speechSynthesis.cancel();const rate=+$('#rateSel').value;let i=0;function go(){if(i>=current.lines.length)return;const u=new SpeechSynthesisUtterance(current.lines[i++]);u.lang='en-GB';u.rate=rate;u.pitch=i%2?1:.92;u.onend=()=>setTimeout(go,120);speechSynthesis.speak(u)}go()}
$('#playBtn').onclick=playAudio;$('#submitBtn').onclick=submit;
function submit(){let score=0,max=1,answerText='';if(current.type==='single'){if(selected.length!==1)return flash('先选一个答案');score=selected[0]===current.correct?1:0;answerText=String.fromCharCode(65+selected[0])}else if(current.type==='multi'){if(selected.length!==2)return flash('选五个选项里的两个');max=2;score=selected.filter(x=>current.correct.includes(x)).length;answerText=selected.map(x=>String.fromCharCode(65+x)).join('/')}else{matchValues=$$('#matchingAnswers select').map(x=>x.value===''?null:+x.value);if(matchValues.some(x=>x===null))return flash('4 个匹配都要选');max=current.correct.length;score=matchValues.filter((x,i)=>current.options[x]===current.correct[i]).length;answerText=matchValues.map(x=>String.fromCharCode(65+x)).join('/')}
const key=current.id,old=state.answers[key]||{attempts:0,correct:0,maxPoints:0,armed:0};old.attempts++;old.correct+=score;old.maxPoints=(old.maxPoints||0)+max;old.armed+=armed?1:0;old.lastAt=Date.now();state.answers[key]=old;state.streak=score===max?(state.streak||0)+1:0;state.bestStreak=Math.max(state.bestStreak||0,state.streak);state.seen[mode]=[...new Set([...(state.seen[mode]||[]),key])].slice(-200);sessionResults.push({q:current,score,max,answerText,armed,lag:current._prepLag});save();idx++;next()}
function flash(t){$('#listenHint').textContent=t;setTimeout(()=>$('#listenHint').textContent='不要回想上一题。答案落下就切。',1200)}
function finish(){speechSynthesis.cancel();state.sessions++;save();show('summary');$('#progressBar').style.width='100%';const score=sessionResults.reduce((n,r)=>n+r.score,0),max=sessionResults.reduce((n,r)=>n+r.max,0),pre=sessionResults.filter(r=>r.armed).length,lag=Math.round(sessionResults.reduce((n,r)=>n+r.lag,0)/Math.max(1,sessionResults.length)/100)/10;$('#sumScore').textContent=score+' / '+max;$('#sumAcc').textContent=Math.round(score/max*100)+'%';$('#sumPre').textContent=Math.round(pre/sessionResults.length*100)+'%';$('#sumLag').textContent=lag+'s';$('#review').innerHTML=sessionResults.map(r=>`<div class="review-item"><b>${r.score===r.max?'✓':'✕'} ${r.q.stem}</b><div class="muted">你的答案：${r.answerText||'—'} · 得分 ${r.score}/${r.max} · ${r.armed?'已上膛':'未主动上膛'}</div><div>${r.q.lines.join(' ')}</div><div><span class="tag">差异轴</span>${r.q.axes.join(' / ')}</div></div>`).join('')}
renderStats();
async function initCloud(){try{const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm');client=mod.createClient(SUPA_URL,SUPA_KEY,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await client.auth.getSession();user=session?.user||null;renderAuth();if(user)await pullMerge();client.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;renderAuth();if(user)await pullMerge()})}catch(e){$('#cloudStatus').textContent='云同步加载失败：'+e.message}}
function renderAuth(){if(user){$('#signedOut').classList.add('hidden');$('#signedIn').classList.remove('hidden');$('#userLabel').textContent=user.email||user.id;$('#cloudStatus').textContent='已登录，训练后会自动同步。'}else{$('#signedOut').classList.remove('hidden');$('#signedIn').classList.add('hidden');$('#cloudStatus').textContent='未登录，本机仍会保存进度。'}}
async function pullMerge(){const {data,error}=await client.from('user_state').select('state').eq('user_id',user.id).maybeSingle();if(error){$('#cloudStatus').textContent='读取云端失败：'+error.message;return}if(data?.state?.progress){state=merge(state,data.state.progress);localStorage.setItem(LS,JSON.stringify(state));renderStats()}await pushCloud()}
async function pushCloud(){if(!client||!user)return;const {error}=await client.from('user_state').upsert({user_id:user.id,state:{progress:state,client_modified_at:state.updatedAt||Date.now(),app_version:'github-1'}},{onConflict:'user_id'});$('#cloudStatus').textContent=error?'同步失败：'+error.message:'已同步 · '+new Date().toLocaleTimeString()}
function scheduleSync(){if(!user)return;clearTimeout(syncTimer);syncTimer=setTimeout(pushCloud,700)}
$('#loginBtn').onclick=async()=>{const {error}=await client.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)$('#cloudStatus').textContent='登录失败：'+error.message};
$('#signupBtn').onclick=async()=>{const {data,error}=await client.auth.signUp({email:$('#email').value.trim(),password:$('#password').value});$('#cloudStatus').textContent=error?'注册失败：'+error.message:(data.session?'注册并登录成功':'注册成功，请查邮箱完成验证后登录')};
$('#logoutBtn').onclick=()=>client.auth.signOut();$('#syncBtn').onclick=pushCloud;initCloud();