const topics=['research project','campus survey','museum study','presentation plan','fieldwork','business case study','environmental project','media research','psychology experiment','design assignment','tourism project','education study'];
const names=['Maya','Lewis','Nina','Owen','Sara','Tom','Lena','Ryan','Eva','Noah','Ivy','Jack'];
const singleSeeds=[
 ['What do the students agree was the main weakness of the previous sessions?',['they were held at inconvenient times','there were too few sessions','the speakers lacked relevant experience'],2,['timing','number','speaker'],['There were plenty of sessions, and the timing was actually fine.','What disappointed me was that the speakers often knew the theory but had very little real experience.']],
 ['Why did the students change their original method?',['it would take too long','it might produce unreliable results','it required equipment they could not access'],1,['time','reliability','equipment'],['Time was not the issue, and the lab offered us the equipment.','The real concern was whether people would answer honestly, so the results might not be dependable.']],
 ['What surprised them most about the first results?',['the sample was smaller than expected','one group performed much better','the pattern was different from earlier studies'],2,['sample','group performance','research pattern'],['The number of participants was almost exactly what we planned.','But the overall pattern went against what previous studies had suggested.']],
 ['What does the tutor recommend they improve first?',['the introduction','the evidence used','the conclusion'],1,['opening','evidence','ending'],['The opening is clear and the conclusion is concise.','I would strengthen the middle by using more convincing evidence for your claims.']],
 ['What problem did they have during data collection?',['participants misunderstood a question','some recordings were unusable','too many people cancelled'],0,['question clarity','recordings','cancellations'],['Only two people cancelled, and the recordings were clear.','The bigger issue was that several participants interpreted one question in a completely different way.']],
 ['What do they decide to do next?',['collect more data','rewrite the questionnaire','ask the tutor for feedback'],2,['more data','rewrite','tutor feedback'],['I do not think another round of data collection will solve it.','Before changing the questionnaire, let us show the problem to our tutor and get her view.']],
 ['Why is one source considered more useful?',['it is more recent','it explains the method clearly','it includes a larger sample'],1,['date','method clarity','sample size'],['It is actually a little older and the sample is not especially large.','What makes it useful is how clearly the researchers explain every stage of the method.']],
 ['What are they most concerned about in the presentation?',['keeping within the time limit','making the slides attractive','answering questions afterwards'],0,['time','slides','Q&A'],['The slides already look professional, and I am not too worried about questions.','My concern is that we still have too much material for a ten-minute slot.']]
];
const multiSeeds=[
 ['Which TWO problems do the students identify with the pilot study?',['the instructions were unclear','the room was too noisy','the sample was too small','the software was difficult to use','the session took too long'],[0,2],['instructions','noise','sample','software','time'],['The room was quiet and the software worked without trouble.','What worried me was that several people did not understand the instructions, and with only twelve participants the sample was much too small.']],
 ['Which TWO changes do they decide to make?',['shorten the introduction','add another example','remove a graph','reorder two sections','change the final recommendation'],[1,3],['shorter intro','extra example','remove graph','reorder','new ending'],['I would keep the introduction and the graph.','But another example would make the argument clearer, and the order of the middle two sections should be reversed.']],
 ['Which TWO strengths of the source do they mention?',['recent publication date','clear explanation','large dataset','well-known author','useful comparison'],[1,4],['recent','clear','large data','famous author','comparison'],['It is not especially recent and the author is not famous.','What I liked was the very clear explanation and the comparison between two different groups.']],
 ['Which TWO mistakes does the student admit making?',['focusing too much on appearance','ignoring customer feedback','trying to copy competitors','spending too much money','failing to plan ahead'],[0,4],['appearance','feedback','copying','money','planning'],['I did listen to customers and I was not trying to copy anyone.','Looking back, I cared far too much about how everything looked, and I did not plan the work far enough in advance.']]
];
const matchSeeds=[
 ['Match each student with the main task they will do.',['analyse data','contact participants','design slides','check references','write conclusion'],['contact participants','analyse data','check references','design slides'],['Maya says she is happy to email everyone and arrange the interviews.','Lewis prefers working with numbers, so he will handle the data analysis.','Nina offers to make sure every source is correctly referenced.','Owen says visual design is his strength, so he will prepare the slides.']],
 ['Match each section with the tutor’s main comment.',['needs clearer evidence','too detailed','well organised','repeats an earlier point','needs a stronger example'],['well organised','needs clearer evidence','too detailed','needs a stronger example'],['For the introduction, the structure is already very clear.','In the methods section, several claims need stronger evidence.','The results section gives more detail than the audience needs.','The conclusion would be more persuasive with one concrete example.']],
 ['Match each research method with the students’ view.',['too expensive','easy to organise','likely to be biased','gives rich detail','takes too much time'],['likely to be biased','gives rich detail','easy to organise','takes too much time'],['An online poll might push people toward certain answers, so bias is the concern.','Interviews take effort, but they give us rich and detailed responses.','A short observation task would be straightforward to organise.','A diary study could work, though waiting several weeks would take too much time.']]
];
function clone(x){return JSON.parse(JSON.stringify(x))}
function seeded(arr,i){return arr[i%arr.length]}
function makeSingle(i){const s=clone(seeded(singleSeeds,i));return{id:'s'+i,type:'single',stem:s[0].replace('students',i%2?'students':'researchers'),options:s[1],correct:s[2],axes:s[3],lines:s[4],topic:seeded(topics,i)}}
function makeMulti(i){const s=clone(seeded(multiSeeds,i));return{id:'m'+i,type:'multi',stem:s[0],options:s[1],correct:s[2],axes:s[3],lines:s[4],topic:seeded(topics,i+3)}}
function makeMatching(i){const s=clone(seeded(matchSeeds,i));return{id:'x'+i,type:'matching',stem:s[0],options:s[1],correct:s[2],axes:s[1],lines:s[3],topic:seeded(topics,i+6)}}
const BANK={single:Array.from({length:80},(_,i)=>makeSingle(i)),multi:Array.from({length:24},(_,i)=>makeMulti(i)),matching:Array.from({length:24},(_,i)=>makeMatching(i))};

export {names,BANK};
